# Generated by Django 3.1.2 on 2020-10-15 19:09

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('post_img', models.CharField(max_length=350)),
                ('post_description', models.TextField()),
                ('pric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
            ],
        ),
    ]
