# Generated by Django 3.1.2 on 2020-10-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
